In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
y

tensor([[0.7637, 0.9212, 0.4748, 0.3509, 0.0263],
        [0.7434, 0.2714, 0.7266, 0.7109, 0.8146]])

In [6]:
# reshape
y.view([1,10])

tensor([[0.7637, 0.9212, 0.4748, 0.3509, 0.0263, 0.7434, 0.2714, 0.7266, 0.7109,
         0.8146]])