In [4]:
import torch
import torchvision
from torchvision import transforms, datasets

train = datasets.MNIST("", train = True, download = True,
                      transform = transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("", train = False, download = True,
                      transform = transforms.Compose([transforms.ToTensor()]))

trainset = torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset  = torch.utils.data.DataLoader(test,  batch_size=10, shuffle=True)

In [22]:
type(train)

torchvision.datasets.mnist.MNIST

In [5]:
import torch.nn as nn
import torch.nn.functional as F

In [6]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(28*28, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.fc4 = nn.Linear(64, 10) # 10 classes
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return F.log_softmax(x, dim=1)

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=10, bias=True)
)


In [7]:
X = torch.rand(28,28)
X = X.view(-1, 28*28)

In [8]:
output = net(X)
output

tensor([[-2.2460, -2.3058, -2.3153, -2.3613, -2.2639, -2.2549, -2.2464, -2.3105,
         -2.3159, -2.4196]], grad_fn=<LogSoftmaxBackward>)

In [24]:
import torch.optim as optim

optimizer = optim.Adam(net.parameters(), lr=1e-3)

EPOCHS = 3
for epoch in range (EPOCHS):
    for data in trainset:
        X,y = data
        
        break

tensor([0, 5, 1, 8, 9, 8, 7, 4, 3, 1])
tensor([9, 6, 2, 8, 3, 0, 3, 6, 0, 5])
tensor([8, 2, 8, 3, 1, 7, 3, 9, 4, 8])
